/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CodeChallengePetShelter;

public class App {

    public static void main(String[] args) {
        AnimalShelter animalShelter = new AnimalShelter();
        animalShelter.enqueue(new Animal("dog"));
        animalShelter.enqueue(new Animal("cat"));
        animalShelter.enqueue(new Animal("cat"));
        animalShelter.listAnimals();
        animalShelter.dequeue("dog");
        animalShelter.listAnimals();
        animalShelter.enqueue(new Animal("lizard"));
        animalShelter.listAnimals();
        animalShelter.dequeue("cat");
        animalShelter.listAnimals();
    }
}
